### PR TITLE
Josho/dynamic schedule

### LINKED ISSUE #249: Bug: Courses scheduled to end after 8pm are not displayed correctly on calendar
### Description:
When adding labs that extend past 8:00pm the UI will make the lab appear to end at 8:00pm instead. 

### Steps to reproduce the behaviour/bug/issue:
1. navigate to: https://courseup.vikelabs.ca/
2. select fall or winter term
3. add course with evening lab (eg. 2021-09 Phys 323, using lab B03 or Phys 229 using lab B04)
4. Open calendar
5. Scroll to bottom of calendar

### Expected:
One of the following:
1. Calendar is extended to accommodate these end times.
2. Courses ending between 8:00pm and 9:00pm are show correctly, and courses that end after 9:00pm are given a note on the calendar entry of the actual end time. 
3. Removing the time block after 7:59pm and then the same output as (2.) above except the cut-off is 8:00pm instead of 9:00pm

#### Screenshots
The courses not extending past 8:00pm

image

The course which should end before 9:00pm but after 8:00pm

image

The course with a lab that should end after 9:00pm

image

#### Desktop info:
 - OS: Windows 10 21H1 Build 19043.1110
 - Browser: Firefox, V90.0.2

### PR DESCRIPTION
**Pull request by JoshoTheMosho**
# Description

Fixes a bug with courses not displaying if they go past 8:00pm. Now, the schedule adjusts to fit in all courses selected dynamically.

Closes #249

### Before

image

### After

image

image

## General Comments

I would like to work on adjusting the size of the calendar to fit in weekend classes/exams when needed -- new branch (dynamic_days_schedule) works on this feature.

### CODE REVIEW

**Comment by zthh626** [comment]
Hey Josho,
You have some linting to do, if you go to files changed you should see them under `src/pages/scheduler/components/SchedulerCalendar.tsx`.

File: src/pages/scheduler/components/SchedulerCalendar.tsx [hunk 1]
```diff
@@ -178,6 +180,17 @@ export function SchedulerCalendar({ calendarEvents }: SchedulerCalendarProps): J
       try {
         if (calendarEvent.meetingTime.time.indexOf('TBA') !== -1) return;
 
+        // Looking for courses between 1pm - 11pm
+        if (
+          calendarEvent.meetingTime.time.split(`- `)[1].split(` `)[1] == `pm` &&
+          parseInt(calendarEvent.meetingTime.time.split(`- `)[1].split(':')[0]) != 12
+        ) {
+          let theTime = parseInt(calendarEvent.meetingTime.time.split(`- `)[1].split(`:`)[0]) + 12;
```
Comment (zthh626) [inline src/pages/scheduler/components/SchedulerCalendar.tsx:188]: Instead of parsing it, we can get it directly from the event inside `events`

**Review by zthh626 — CHANGES_REQUESTED** [review]

File: src/common/header/components/GitHubButton.tsx [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+      fontSize="35px"
+      isRound
+      aria-label="Open GitHub Repo"
+      _hover={{
+        color: 'gray.500',
+      }}
+      icon={<AiFillGithub />}
+    />
+  );
+}
```
Comment (aomi) [inline src/common/header/components/GitHubButton.tsx:21]: Why is this in here?

File: src/pages/scheduler/components/SchedulerCalendar.tsx [hunk 3]
```diff
@@ -149,12 +150,26 @@ export const SchedulerCalendar = ({ term, courseCalendarEvents = [] }: Scheduler
         // if event does not have a scheduled time, move on.
         if (calendarEvent.meetingTime.time.indexOf('TBA') !== -1) return;
 
+        if (
+          calendarEvent.meetingTime.time.split(`- `)[1].split(` `)[1] === `pm` &&
+          parseInt(calendarEvent.meetingTime.time.split(`- `)[1].split(':')[0]) !== 12
+        ) {
+          let theTime = parseInt(calendarEvent.meetingTime.time.split(`- `)[1].split(`:`)[0]) + 12;
+          if (theTime > latestHour && theTime < 24) {
+            setLatestHour(theTime + 1);
```
Comment (aomi) [inline src/pages/scheduler/components/SchedulerCalendar.tsx:159]: `theTime` is a bit sus as a variable name. Also it can be `const`.

File: src/pages/scheduler/components/SchedulerCalendar.tsx [hunk 4]
```diff
@@ -149,12 +150,26 @@ export const SchedulerCalendar = ({ term, courseCalendarEvents = [] }: Scheduler
...
+
+        const courseStartDate = new Date(startEndDates[0].replace(',', '') + ' 00:00:00 GMT');
+
         // check cache, if it exists, use it otherwise parse and set value in cache
         if (!EVENTS_CACHE[key]) {
           EVENTS_CACHE[key] = parseMeetingTimes(calendarEvent);
         }
 
-        const { lower: ruleLower, upper: ruleUpper, startDate: courseStartDate } = EVENTS_CACHE[key];
+        const { lower: ruleLower, upper: ruleUpper } = EVENTS_CACHE[key];
```
Comment (aomi) [inline src/pages/scheduler/components/SchedulerCalendar.tsx:172]: Did `startDate` just get removed since it's not used?

File: src/pages/scheduler/components/SchedulerCalendar.tsx [hunk 5]
```diff
@@ -201,14 +221,14 @@ export const SchedulerCalendar = ({ term, courseCalendarEvents = [] }: Scheduler
...
-  }, [courseCalendarEvents, computedSelectedDate]);
+  }, [courseCalendarEvents, computedSelectedDate, latestHour]);
 
   return (
     <Calendar<CustomEvent>
       localizer={localizer}
       events={events}
       min={set(today, { hours: 8, minutes: 0 })}
-      max={set(today, { hours: 20, minutes: 0 })}
+      max={set(today, { hours: latestHour, minutes: 0 })}
```
Comment (aomi) [inline src/pages/scheduler/components/SchedulerCalendar.tsx:231]: nit: could it be `maxHour` as the variable name?

File: src/common/header/components/GitHubButton.tsx (hunk 2 above)
Comment (keithradford) [reply src/common/header/components/GitHubButton.tsx:21]: yeah this file can be deleted, it's out of date and has been moved elsewhere

File: src/pages/scheduler/components/SchedulerCalendar.tsx (hunk 3 above)
Comment (keithradford) [reply src/pages/scheduler/components/SchedulerCalendar.tsx:159]: @JoshoTheMosho This doesn't need to be here anymore, lines 183-187 replaced this code 😃

File: src/pages/scheduler/components/SchedulerCalendar.tsx (hunk 4 above)
Comment (JoshoTheMosho) [reply src/pages/scheduler/components/SchedulerCalendar.tsx:172]: Its implemented again, and the redundant startDate declarations are being removed

**Review by aomi — APPROVED** [review]
