### PR TITLE
fix: Responsiveness - Registration Page

### LINKED ISSUE #222: Responsiveness - Registration Page
**Describe the bug**

The responsiveness of the registration page has a few issues with text cutoff and missing spacing border around text.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to https://courseup.vikelabs.ca/registration/202109
2. Resize browser and view issues.

**Expected behavior**

The text has adequate spacing between the sides of the browser, and the text doesn't get cutoff. 

**Screenshots**

Capture d’écran, le 2021-06-16 à 19 38 41

Capture d’écran, le 2021-06-16 à 19 38 55

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: Latest

**Additional context**

This shouldn't require any additional design changes.

### PR DESCRIPTION
**Pull request by FlyteWizard**
# Overview

Closes #222 

Adding additional responsiveness to an already responsive component (registration page). Updated instructions to be accessible and mobile friendly.

Note: https://github.com/VikeLabs/courseup/issues/227 has been created, as it requires a more higher level change.

### Old:

Desktop: 
Capture d’écran, le 2021-06-19 à 13 25 28

Mobile:
Capture d’écran, le 2021-06-19 à 13 26 28

### New:

Desktop:
Capture d’écran, le 2021-06-19 à 13 25 44

Mobile:
Capture d’écran, le 2021-06-19 à 13 26 10

Capture d’écran, le 2021-06-19 à 13 29 43

### CODE REVIEW

**Comment by FlyteWizard** [comment]
Preview: https://flytewizard-courseup-p777q5jx2rg59-3000.githubpreview.dev/registration/202109

File: src/pages/registration/components/RegistrationHeading.tsx [hunk 1]
```diff
@@ -12,90 +12,97 @@ export function RegistrationHeading() {
...
+            </ListItem>
+            <ListItem>
+              Hit{' '}
+              <Text as="span" fontWeight="bold">
+                Submit Changes
+              </Text>
+              , and you’re registered!
+            </ListItem>
+          </OrderedList>
+          For more information, visit UVic's guide on "
```
Comment (keithradford) [inline src/pages/registration/components/RegistrationHeading.tsx:92]: such a nice touch 🔥

**Review by keithradford — APPROVED** [review]
LGTM, thanks for doing this!
