### PR TITLE
Use memory for seat data

### LINKED ISSUE #455: Bug: Copy CRN Freezes the Page
**Describe the Bug/Issue**
Clicking "Copy CRN" in the Register page causes the page to freeze.

**To Reproduce**

1. Add courses to timetable
2. Go to Register page
3. Click the copy button next to the course CRN

The page is now unresponsive but the CRN has been copied.

**Expected Behaviour**
The page should continue to function.

**Demo**

https://user-images.githubusercontent.com/7586345/225122870-b10e8113-cef1-496a-9a2b-a79a28a07ccc.mov

**Runtime**

- Firefox 110.0.1
- macOS Ventura 13.2.1
- MacBook Air M2

### PR DESCRIPTION
**Pull request by JoshoTheMosho**
Avoids an infinite rendering loop causing crashes or freezing on the registration page

# Description
Modify seats to use memory as previously it would update infinitely causing issues

Closes #455

## Checklist

- [x] The code follows all style guidelines.
- [x] The code passes all required tests.
- [ ] The code is documented.
- [ ] The code includes tests.
- [x] I have self-reviewed my changes and have done QA.

### CODE REVIEW

File: src/pages/registration/containers/CourseContainer.tsx [hunk 1]
```diff
@@ -29,29 +29,31 @@ export function CourseContainer({ course }: Props) {
   const termType = term as Term;
   const mode = useDarkMode();
 
-  const { data: sections, loading } = useSections({
+  let { data: sections, loading } = useSections({
```
Comment (keithradford) [inline src/pages/registration/containers/CourseContainer.tsx:32]: Any reason for this change?

**Review by keithradford — APPROVED** [review]
Thanks for tackling this so fast!
