### PR TITLE
fix: Course Title and Subtitle Visual Bug w/ Add/Delete Button on Course Page

### LINKED ISSUE #345: Bug (visual): Classes with long titles squish add/remove from timetable button
**Describe the Bug/Issue**

For classes with long titles or on smaller screens the `Add to timetable`/`Remove from timetable` button gets squished and the content of it is cut off. It should have a minimum width so it's always legible with appropriate padding and should force longer titles onto a new line earlier.

**To Reproduce**

Steps to reproduce the behaviour/bug/issue:
1.  Go here https://courseup.vikelabs.ca/calendar/202205/SENG?pid=Hkpylt674
1.  Make your screen width small enough that the button starts to become ineligible (It cuts of for my 14 inch laptop on fullscreen)

**Expected Behaviour**

It always looks the same/doesn't scale like this

**Screenshots**

Screen Shot 2022-03-06 at 4 34 02 PM

**Desktop/Mobile**

 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional Context**

### PR DESCRIPTION
**Pull request by FlyteWizard**
# Description

Proposed Fix: The course title and subtitle are now permanently on two lines. The button in centered as previously, and is start when in smaller screens. As well, the button is icon only at smaller screens.

Took inspiration from https://github.com/VikeLabs/courseup/pull/320

Closes #345 

### Before

Capture d’écran, le 2022-03-13 à 23 12 25
Capture d’écran, le 2022-03-13 à 23 12 33
Capture d’écran, le 2022-03-13 à 23 12 41
Capture d’écran, le 2022-03-13 à 23 12 48

### After

Capture d’écran, le 2022-03-13 à 23 12 59
Capture d’écran, le 2022-03-13 à 23 13 06
Capture d’écran, le 2022-03-13 à 23 13 10
Capture d’écran, le 2022-03-13 à 23 13 18

---

Capture d’écran, le 2022-03-13 à 23 14 30
Capture d’écran, le 2022-03-13 à 23 14 37
Capture d’écran, le 2022-03-13 à 23 14 41
Capture d’écran, le 2022-03-13 à 23 14 48

## Checklist

- [x] The code follows all style guidelines.
- [x] The code passes all required tests.
- [x] The code is documented.
- [ ] The code includes tests.
- [x] I have self-reviewed my changes and have done QA.

## General Comments

Let me know if these changes need refinement based on your design vision. The breakpoints and font size can be modified.

### CODE REVIEW

File: src/pages/calendar/containers/Content.tsx [hunk 1]
```diff
@@ -57,31 +57,55 @@ export function Content({ term }: ContentProps): JSX.Element {
...
-              rightIcon={courseIsSaved ? <MdDelete /> : <MdAdd />}
-              onClick={handleBookmarkClick}
-              colorScheme={courseIsSaved ? 'red' : 'green'}
-              size="sm"
-              disabled={loading}
-            >
-              {courseIsSaved ? 'Remove from Timetable' : 'Add to Timetable'}
-            </Button>
+            <>
+              <Button
```
Comment (keithradford) [inline src/pages/calendar/containers/Content.tsx:85]: You can leave the button as is for now, I'm making it responsive with some context relevant to the PR you mentioned. Since the page itself isn't responsive yet (until that PR goes up) it's not a big deal to stay the same and get squishy

**Review by keithradford — COMMENTED** [review]
This is a great change, wayyyy better all around

**Comment by aomi** [comment]
@FlyteWizard Would putting the button on the same row as the eg. SENG 475 would be a good idea? 
I'm not really feeling the course title wrapping dependent on the state of the button. This doesn't seem to happen on the mobile view.

**Comment by FlyteWizard** [comment]
@aomi I'm not sure I understand.

Are you referring to the button being in the middle? 

Capture d’écran, le 2022-03-14 à 19 43 20

And instead you want it to be ...

Capture d’écran, le 2022-03-14 à 19 46 04

Let me know if I understood correctly or not 👍

**Comment by aomi** [comment]
@FlyteWizard yup! I was specifically looking at your first two "after' screenshots and noticed the difference in wrapping. 

If we move the button up a smidge the wrapping will be consistent regardless of the button state. I believe the components would need to moved around a bit to get the button and subject/code to be on the same row and the title to have its own row (as to not wrap).

**Comment by FlyteWizard** [comment]
Capture d’écran, le 2022-03-14 à 23 20 02
Capture d’écran, le 2022-03-14 à 23 20 09
Capture d’écran, le 2022-03-14 à 23 20 22
Capture d’écran, le 2022-03-14 à 23 20 30
Capture d’écran, le 2022-03-14 à 23 21 18
Capture d’écran, le 2022-03-14 à 23 21 25
Capture d’écran, le 2022-03-14 à 23 21 32
Capture d’écran, le 2022-03-14 à 23 21 39

**Review by aomi — APPROVED** [review]
LGTM. Thanks for doing this change.
