### PR TITLE
Chore: Fix search header light more, landing overflow and frontend dependencies

### LINKED ISSUE #209: Bug: Overflow Hidden on Landing Page
**Describe the bug**

The landing page has overflow set to hidden, and the text is not scrollable, meaning text gets cut off. 

**To Reproduce**

1.  Visit https://courseup.vikelabs.ca.
2. View page in "non standard" format.
3. View that the text gets cut off. 

**Expected behaviour**

The text is not cutoff and is still viewable/scrollable.

**Screenshots**

Capture d’écran, le 2021-06-10 à 06 43 41

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: Latest

### PR DESCRIPTION
**Pull request by aomi**
# Description

I didn't QA https://github.com/VikeLabs/courseup/pull/270 properly and let a bug slip where light mode broke :facepalm: and this fixes that issue.
Also closes #209 and updates ALL front-end dependencies that can be updated.
ts-jest cannot be updated yet to due some internal changes. 

## Checklist

- [ ] The code follows all style guidelines.
- [ ] The code passes all required tests.
- [ ] The code is documented.
- [ ] The code includes tests.
- [ ] I have self-reviewed my changes and have done QA.

### CODE REVIEW

**Comment by FlyteWizard** [comment]
I don't think this addresses the overflow issues. In all the cases below the text still gets cut off. 

Capture d’écran, le 2021-08-14 à 19 40 15

Capture d’écran, le 2021-08-14 à 19 40 27

Capture d’écran, le 2021-08-14 à 19 40 55

File: src/pages/home/index.tsx [hunk 1]
```diff
@@ -8,7 +9,9 @@ export function Home(): JSX.Element {
   return (
     <Flex h="100vh" direction="column">
       <Header />
-      <Landing />
+      <Center h="100%">
+        <Landing />
+      </Center>
```
Comment (FlyteWizard) [inline src/pages/home/index.tsx:14]: The `<Center></Center>` should be in the `<Landing />`.

Comment (aomi) [reply src/pages/home/index.tsx]: My rational was not to assume layout in the `<Landing/>` component itself since it might be used in other ways.

**Review by keithradford — APPROVED** [review]
