### PR TITLE
Joaquin/ampersand issue

### LINKED ISSUE #395: Bug: Return `&` instead of `&amp;` in backend
**Describe the Bug/Issue**

**To Reproduce**

Steps to reproduce the behaviour/bug/issue:

1. Go to any course that has a location with & (https://courseup.vikelabs.ca/calendar/202205/CSC?pid=Bk_cy_a7V)
1. scroll to location

**Expected Behaviour**

Should say `&` instead of `&amp;`

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Schorcher5**
# Description

Fixed &amp; issue by adding a new function (formatBuilding) in functions/src/utils.ts the replaces &amp; with &. Function is then used in functions/src/sections/Section.controllers.ts to format building strings correctly. Tested only in a local environment. Testing in production is still required (don't have access/don't know how to run code in production).

Closes #395 

## Screenshots

Can't take screen shots on my current machine but change can be seen by searching csc 225, clicking on the class, and looking at the building description.

### Before

"Human &amp; Social Development A240

### After

"Human & Social Development A240

## Checklist

- [ ] The code follows all style guidelines.
- [ ] The code passes all required tests.
- [ ] The code is documented.
- [ ] The code includes tests.
- [ ] I have self-reviewed my changes and have done QA.

## General Comments

Let me know of any improvements or changes that are needed. Haven't worked on a project like this before so code my not be the greatest.

### CODE REVIEW

**Comment by keithradford** [comment]
`npm run lint:fix` should solve the CI failing

**Comment by Schorcher5** [comment]
Where do I run npm run lint:fix?

**Comment by keithradford** [comment]
> Where do I run npm run lint:fix?

In the root directory and in './functions'. I think the error is in '/functions' but run both to be safe

File: functions/src/sections/Section.controller.ts [hunk 1]
```diff
@@ -50,16 +50,19 @@ export class SectionsController extends Controller {
...
           scheduleType: s.scheduleTypeDescription,
           instructors: s.faculty.map(
             (f) => f.displayName + `${f.primaryIndicator ? ' (P)' : ''}`
           ),
-          building: m.meetingTime.buildingDescription ?? undefined,
+          building:
+            formatBuilding(m.meetingTime.buildingDescription) ?? undefined,
           buildingAbbreviation: Buildings.get(
-            m.meetingTime.buildingDescription ?? ''
+            formatBuilding(m.meetingTime.buildingDescription) ?? ''
```
Comment (keithradford) [inline functions/src/sections/Section.controller.ts:65]: Just want to double check you QA'd this change, if you add a course that has `&` to your timetable is the abbreviated version showing up in the timetable?

`Buildings.get` is accessing a mapping between the full name and the abbreviated name so since you're passing in something potentially different now with the `formatBuilding` function I just want to double check this

**Review by keithradford — COMMENTED** [review]
Thanks for the PR! Just the one question and I'll approve if it's good :)

**Review by keithradford — APPROVED** [review]
